services:
  backend:
    build: .
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
    volumes:
      - .:/app
      - /app/.venv
      # - ./.env:/app/.env
      # - ./db.sqlite:/app/db.sqlite
    ports: 
      - "5046:5046"
